<?php
/*
 * Copyright (c) 2023 Keira Dueck <sylae@calref.net>
 * Use of this source code is governed by the MIT license, which
 * can be found in the LICENSE file.
 */

namespace WormRP\Controller;

use Nin\ListViews\ModelListView;
use Nin\Nin;
use WormRP\Controller;

class Admin extends Controller
{
    public function beforeAction($action)
    {
        $this->addBreadcrumb("Administrative", "/admin");

        if (!Nin::user()->isAdmin) {
            $this->displayError("not an admin >:(", 403);
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionUserList(int $page = 1)
    {
        $this->addBreadcrumb("User Management", "/admin/users");
        $query = \WormRP\Model\User::beginQuery()->select()->orderby('username', 'ASC');

        $users = new ModelListView($this, $page, $query);
        $users->perpage = 100;


        $this->render('admin.users', array(
            'users' => $users,
        ));
    }

    public function actionUserFlags(int $idUser)
    {
        /** @var \WormRP\Model\User $user */
        $user = \WormRP\Model\User::findByPk($idUser);

        if (!$user) {
            $this->displayError("unknown user");
            return;
        }
        $this->addBreadcrumb("User Management", "/admin/users");
        $this->addBreadcrumb($user->username, "/admin/users/" . $user->idUser);

        if (isset($_POST['csrf'])) {
            if ($_POST['csrf'] !== \Nin\Nin::getSession('csrf_token')) {
                $this->displayError('Invalid token.');
                return;
            }

            $user->isAdmin = array_key_exists("admin", $_POST);
            $user->isMod = array_key_exists("mod", $_POST);
            $user->isApprover = array_key_exists("approver", $_POST);
            $user->isBanned = array_key_exists("banned", $_POST);
            $user->isDootable = array_key_exists("doots", $_POST);
            $user->save();
        }


        $this->render("admin.userflags", ['v' => $user]);
    }
}
