<?php
/*
 * Copyright (c) 2023 Keira Dueck <sylae@calref.net>
 * Use of this source code is governed by the MIT license, which
 * can be found in the LICENSE file.
 */

namespace WormRP\Controller;

use Nin\ListViews\ModelListView;
use Nin\Nin;
use WormRP\Controller;

class Admin extends Controller
{
    public function beforeAction($action)
    {
        $this->addBreadcrumb("Administrative", "/admin");

        if (!Nin::user()->isAdmin) {
            $this->displayError("not an admin >:(", 403);
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionUserList(int $page = 1)
    {
        $query = \WormRP\Model\User::beginQuery()->select()->orderby('username', 'ASC');

        $users = new ModelListView($this, $page, $query);
        $users->perpage = 100;


        $this->render('admin.users', array(
            'users' => $users,
        ));
    }
}
