name: 'Deploy update'

on:
  push:
    branches:
      - main
    
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Secure Webhook
      uses: navied/secure-webhook@0.2.1
      with:
        url: https://wormrp.com/api/deploy
        data: '{ "this": "doesnt really matter lmao" }'
        hmacSecret: ${{ secrets.DEPLOY_KEY }}
