name: 'Sentry integration'

on:
  push:
    branches:
      - main
    
jobs: 
  generate-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
      fetch-depth: 0
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ SENTRY_ORG }}
        SENTRY_PROJECT: ${{ SENTRY_PROJECT }}
      with:
        environment: production
